### ISSUE TITLE
Crash during evaluation of ConvTasNet recipe with 16000 Hz, enh_single

### ISSUE THREAD

**Issue by tux-coder** [mpariente/asteroid#139]
Hello,

I tried the ConvTasNet recipe (wham dataset),

the current evaluation script provided (eval.py) crashes when the model has been trained with these parameters (16000 Hz, enh_single task) : 

```
data:
  mode: min
  nondefault_nsrc: null
  sample_rate: 16000
  task: enh_single
  train_dir: data/wav16k/min/tr
  valid_dir: data/wav16k/min/cv
filterbank:
  kernel_size: 32
  n_filters: 512
  stride: 16
main_args:
  exp_dir: exp/train_convtasnet__16k_enh_single_wham_v5/
  gpus: '-1'
  help: null
masknet:
  bn_chan: 128
  hid_chan: 512
  mask_act: relu
  n_blocks: 8
  n_repeats: 3
  n_src: 1
  skip_chan: 128
optim:
  lr: 0.001
  optimizer: adam
  weight_decay: 0.0
positional arguments: {}
training:
  batch_size: 4
  early_stop: true
  epochs: 200
  half_lr: true
  num_workers: 8
```
the evaluation step in run.sh crashes, when the script tries to create wav files, an "index out of range" error message occurs : 

```
Traceback (most recent call last):
  File "eval.py", line 118, in <module>
    main(arg_dic)
  File "eval.py", line 78, in main
    conf['sample_rate'])
  File ".../lib/python3.7/site-packages/soundfile.py", line 313, in write
    channels = data.shape[1]
IndexError: tuple index out of range
```
Lines in eval.py file that trigger the bug : 

```
            #Loop over the sources and estimates
            for src_idx, src in enumerate(sources_np):
                sf.write(local_save_dir + "s{}.wav".format(src_idx+1), src,
                         conf['sample_rate'])
            for src_idx, est_src in enumerate(est_sources_np):
                sf.write(local_save_dir + "s{}_estimate.wav".format(src_idx+1),
                         est_src, conf['sample_rate'])
```
